---
# tasks/plugins.yml: Deploy available checks/plugins/handlers/filters/mutators

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Set the client ip correctly
    block:

      - name: set the ip
        lineinfile:
          path: /etc/sensu/conf.d/client.json
          regexp: '(.*)address(.*)'
          line: "  \"address\" : \"{{ hostvars[inventory_hostname]['ansible_'+sensu_client_networkadapter_name]['ipv4']['address'] }}\", "

    when:  
      - sensu_client_networkadapter_name is defined
      - sensu_client_networkadapter_name != ""
